from os.path import join as osjoin
from itertools import product
import numpy as np

# Main paths
PROJ_HOME = open('PROJ_HOME_DIR').read().strip()
DATA_DIR = osjoin(PROJ_HOME, 'graph')


# Raw dataset
NETWORK_LIST = ['ca-HepTh']
INPUT_FILE_LIST = [osjoin(DATA_DIR, network_name + '.elist')
                   for network_name in NETWORK_LIST]

# Splitted dataset
NUMBER_OF_TEST_SET = 1
SPLITTED_FILE_DIRS = [osjoin(DATA_DIR, network_name + '_' + str(index))
                      for index in range(NUMBER_OF_TEST_SET) for network_name in NETWORK_LIST]
RESULT_FILES = [osjoin(directory, 'result.tsv')
                          for directory in SPLITTED_FILE_DIRS]
                          
REPETITION_PER_SAMPLE = 1
NUMBER_OF_WORKERS_FOR_TRAINING = 4
LAMBDS = np.linspace(0.1, 1, 10)
DIMS = [8, 16, 32, 64, 128]

# Computation envirioment
RESULT_FILE = osjoin(PROJ_HOME, 'result.tsv')


rule all:
    input:
        RESULT_FILES

rule link_prediction:
    input:
        osjoin(DATA_DIR, "{name}_{index}", "network.elist"),
        osjoin(DATA_DIR, "{name}_{index}", "test_edges.pkl"),
        osjoin(DATA_DIR, "{name}_{index}", "negative_edges.pkl"),
    output:
        osjoin(DATA_DIR, "{name}_{index}", "result.tsv"),
    run:
        for lambd, dim in product(*[LAMBDS, DIMS]):
            shell(
                'python3 script/link_prediction.py {input} {RESULT_FILE} {lambd} {dim} {NUMBER_OF_WORKERS_FOR_TRAINING} {REPETITION_PER_SAMPLE}')


rule train_test_set_split:
    input:
        osjoin(DATA_DIR, "{name}.elist")
    output:
        osjoin(DATA_DIR, "{name}_{index}", "network.elist"),
        osjoin(DATA_DIR, "{name}_{index}", "test_edges.pkl"),
        osjoin(DATA_DIR, "{name}_{index}", "negative_edges.pkl")

    run:
        shell(
            'python3 script/train_test_set_split.py {input} {wildcards.index}')

