from os.path import join as osjoin
from itertools import product
import numpy as np

# Main paths
PROJ_HOME = open('PROJ_HOME_DIR').read().strip()
DATA_DIR = osjoin(PROJ_HOME, 'graph')


# Raw datasets
FILE_LIST = ['ca-HepTh.elist']
FILE_DIRS = [osjoin(DATA_DIR, file) for file in FILE_LIST]
LAMBDS = np.linspace(0.1, 1, 10)
DIMS = [8, 16, 32, 64]

# Computation envirioment
REPETITION = 10
RESULT_FILE = osjoin(PROJ_HOME, 'result.tsv')


rule all:
    input:
        RESULT_FILE


rule link_prediction:
    input:
        FILE_DIRS
    output:
        RESULT_FILE
    run:
        for file, lambd, dim in product(*[FILE_DIRS, LAMBDS, DIMS]):
            shell(
                'python3 script/link_prediction.py {file} {RESULT_FILE} {lambd} {dim} {REPETITION}')
